version: "3.7"

volumes:
  pg_project:


services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bot
    volumes:
      - pg_project:/var/lib/postgresql/data:/db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  
  bot:
    build: bot/
    command:
      - dotnet SantaBot.dll
    ports:
      - 8080:80
    network_mode: bridge
    depends_on:
      - pg_db